### ISSUE TITLE
`Up next` is broken

### ISSUE THREAD

**Issue by mikhaelkh** [Invertex/Gfycat-AutoHD#1]
Instead of next gif there's empty screen.

**Comment by Invertex** [comment]
Thanks for the report, I never have auto-play on so I didn't notice this. 
I believe it should be fixed now after the changes I've made. 
Lemme know if it is for you, cheers.

**Comment by mikhaelkh** [comment]
Now it's fine.
Although I think hidden elements should rather be reported to EasyList or Fanboy Annoyances.

**Comment by Invertex** [comment]
Yeah they should be, but not everyone uses those. And for the first-party adverts asking you to upgrade, those aren't generally something added to adblock lists. I'll think about disabling the third-party adverts removal though once the Adblockers catch up to the site changes.
