### ISSUE TITLE
1.88 not working as expected

### ISSUE THREAD

**Issue by bradenhilton** [Invertex/Gfycat-AutoHD#10]
I understand that there have been some recent changes to the site(s), but it appears that more improvements are required.

1.88 has no effect for me (at least not on Firefox with Violentmonkey), all gfys default to SD and the audio/autoplay toggles don't update their respective variables in the storage.

If I revert to the previous version, or revert https://github.com/Invertex/Gfycat-AutoHD/blob/c448edd95a6e4e34bb6205caeb50908627aa26c7/Gfycat%20AutoHD.user.js#L135 back to what it was previously https://github.com/Invertex/Gfycat-AutoHD/blob/e8ea3c5239fb447f6309c447489282b00a83e711/Gfycat%20AutoHD.user.js#L135 it appears to work as expected on Gyfcat at least.

I did some cursory console log debugging and was unable to find where exactly it's failing.

**Comment by Invertex** [comment]
Yeah I noticed the other day and tried logged too and the quality button is being clicked, so it's confusing what's happening. I'll try to fix it though. Thanks

**Comment by Invertex** [comment]
Fixed :)
