### ISSUE TITLE
Doesn't seem to be working

### ISSUE THREAD

**Issue by LeiAdair** [Invertex/Gfycat-AutoHD#12]

**Comment by LeiAdair** [comment]
attempting to use on redditp.com, does not save settings at all.

**Comment by darkdex52** [comment]
I presume it's the complete giphy/redgifs overhaul that this script isn't working anymore.

**Comment by Invertex** [comment]
Even though it doesn't show HD on the icon in the Redgifs redesign, it is playing the HD stream. If you right-click save the video, you'll see it's not the -mobile.mp4 version. I override the website's stream requests.

I'll try and get the icon to change, but things are working otherwise.

**Comment by LeiAdair** [comment]
![b2CgrH8JEv](https://user-images.githubusercontent.com/41504461/220368297-e47fe773-6cc5-4d14-83ab-a53d2c7488d0.png)
It works for gfycat,  which is replaced by a generic playerbar, but not redgifs. See image attached.
