### ISSUE TITLE
Not working on languages other than English

### ISSUE THREAD

**Issue by ThibaultVlacich** [Invertex/Gfycat-AutoHD#2]
This script is not working for me, and I'm pretty sure it's because my OS/browser is in French, and Gfycat automatically redirects from `https://gfycat.com/slug` to `https://gfycat.com/fr/slug`.

It doesn't seem like there's a setting on Gfycat to change the language, so you're forced to use your browser language.

**Comment by Invertex** [comment]
It's confusing why it still wouldn't work since it's set to match on any path of the gfycat.com domain. I'll have to dig deeper when I get some time.

**Comment by ThibaultVlacich** [comment]
Yeah, I look at the code and couldn't find an obvious explanation as to why this is happening.

But I definitely tested changing the content language in Firefox to English, so it's not redirecting to `/fr` and the script is working in that case. Then I put it back to French, it's not working again.

**Comment by ThibaultVlacich** [comment]
Ok, I found why it is not working. `data-tooltip` value is translated.

`<span class="settings-button" data-tooltip="Qualité">`

**Comment by Invertex** [comment]
Ahh dang, that's understandable though. My rationale was to avoid conflicts with multiple elements that might have a "quality" class name which can be common. I'll see how I can refine it more safely tonight. Thanks.

**Comment by Invertex** [comment]
I've pushed a fix that should work, let me know how it goes!

**Comment by ThibaultVlacich** [comment]
Thanks, it's working.
