### ISSUE TITLE
Not working in Firefox 90.0.2

### ISSUE THREAD

**Issue by mb9023** [Invertex/Gfycat-AutoHD#4]
I didn't catch exactly when it stopped working but I reinstalled the script under Greasemonkey extension and it's still not working in Firefox, but it does work in Chrome. Gfys stay in SD mode on open and audio setting doesn't get remembered so doesn't seem to be working at all.

Name 	Firefox
Version 	90.0.2
Build ID 	20210721174149
Tested on Windows 10 20H2 and Windows 11 Insider Preview

**May be an issue specifically with Greasemonkey as it's working in Tampermonkey now.

**Comment by Invertex** [comment]
Thanks for letting me know.
Unfortunately GreaseMonkey does not have the `GM_addValueChangeListener` feature that TamperMonkey has for detecting persistent settings changes, so I've had to implement a check for if people are running GreaseMonkey now. Shouldn't be any change in functionality though :)
