### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by sjclayton** [Invertex/Gfycat-AutoHD#5]
Not sure exactly when it happened, just noticed it 2 days ago..

Running Chrome 96.0.4664.110 here and Tampermonkey 4.13

**Comment by Invertex** [comment]
Thanks for the report, it should be fixed now once your version updates to 1.80 of the script. You can grab it immediately from here if you prefer: [https://github.com/Invertex/Gfycat-AutoHD/raw/master/Gfycat%20AutoHD.user.js](https://github.com/Invertex/Gfycat-AutoHD/raw/master/Gfycat%20AutoHD.user.js)
