### ISSUE TITLE
Auto show controls

### ISSUE THREAD

**Issue by aelfwine88** [Invertex/Gfycat-AutoHD#9]
I found a nice little feature that enables controls automatically:
https://pastebin.com/6mEfKcmV

I added this to your script myself locally (just copy pasted the main part into processVideo and works) but since I'm far from a coder I have no clue where it would be a good fit actually. So I just leave it here as a feature request so if you find it suiting it would be nice if you can add it.

**Comment by Invertex** [comment]
Thanks for the suggestion, though I'd rather not force generic controls on users.
I believe I've fixed the issue of the regular video controls going invisible at times though!
